---
name: Checks
on : [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Django tests
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Run flake8 linting
        run: docker compose run --rm app sh -c "flake8"
